- name: Remove templated files
  become: true
  become_user: root
  ansible.builtin.file:
    path: "{{ role_path }}/files/templated/{{ item }}"
    state: absent
  loop:
    - sshd.conf
    - motion_mail.py
    - motion.conf
    - motionmail.sh
  listen: "mp_cleanup_handler"
- name: Reboot remote and wait for it to restart
  become: true
  become_user: root
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 5
    test_command: whoami
  delegate_to: "{{ rpi4_coreos_ip }}"
  listen: "mp_reboot_handler"
- name: Remove python
  become: true
  become_user: root
  community.general.rpm_ostree_pkg:
    name: 
      - python
      - python3-libselinux
      - python3-firewall
      - python3-rpm
    state: absent
  delegate_to: "{{ rpi4_coreos_ip }}"
  listen: "mp_finalise_handler"
- name: Set motion_user shell
  become: true
  become_user: root
  ansible.builtin.shell:
    cmd: sudo usermod motion_user -s /sbin/nologin
  delegate_to: "{{ rpi4_coreos_ip }}"
  listen: "mp_finalise_handler"
  notify: "mp_reboot_handler"