- name: Remove templated files
  ansible.builtin.file:
    path: "{{ role_path }}/files/templated/{{ item }}"
    state: absent
  loop:
    - sshd.conf
    - motion_mail.py
    - motion.conf
    - motionmail.sh
  listen: "mp_cleanup_handler"
- name: Reboot remote and wait for it to restart
  become: true
  become_user: root
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 5
    test_command: whoami
  delegate_to: "{{ motioncore_ip }}"
  listen: "mp_reboot_handler"
