- name: Wait for remote to reboot...
  ansible.builtin.wait_for:
    host: "{{ rpi4_coreos_ip }}"
    port: 22
    state: started
- name: Install packages on remote machine * takes a long time! (rpm-ostree) *
  community.general.rpm_ostree_pkg:
    name: "{{ motioncore_pkgs | list }}"
    state: present
  register: pkg_out
  delegate_to: "{{ rpi4_coreos_ip }}"
- debug: var=pkg_out
- name: Reboot if necessary
  command: echo "Machine will reboot"
  notify: "mr_reboot_handler"
  when: >-
    pkg_out['changed'] == True
