---
- debug:
    msg: "Templating files from vars.yaml:"
- name: Template local files
  become: yes
  hosts: localhost
  connection: local
  vars:
    user: "{{ lookup('env', 'USER') }}"
  vars_files:
    "{{ playbook_dir }}/../../vars.yaml"
  tasks:
    - name: Create file template
      ansible.builtin.template:
        src: "{{ playbook_dir  }}/{{ item.src }}"
        dest: "{{ playbook_dir }}/{{ item.dest }}"
        mode: "{{ item.mode }}"
        owner: "{{ item.owner | default(user)}}"
        group: "{{ item.group | default(user)}}"
      loop:
        - { src: 'config.bu.j2', dest: '../provision/files/config.bu', mode: "0640" }
        - { src: 'provisioning.sh.j2', dest: '../provision/files/provisioning.sh', mode: "0540", owner: "root" }
    - debug: var=user
