---
- name: Template local files
  hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  become_user: root
  vars:
    user: "{{ lookup('env', 'USER') }}"
  vars_files:
    "{{ playbook_dir }}/../../vars.yaml"
  tasks:
    - name: Create file template
      ansible.builtin.template:
        src: "{{ playbook_dir  }}/{{ item.src }}"
        dest: "{{ playbook_dir }}/{{ item.dest }}"
        mode: "{{ item.mode }}"
        owner: "{{ item.owner | default(user)}}"
        group: "{{ item.group | default(user)}}"
      loop:
        - { src: 'files/config.bu.j2', dest: '../provision/files/config.bu', mode: "0640" }
        - { src: 'files/provision_image.sh.j2', dest: '../provision/files/provision_image.sh', mode: "0550" }
    - debug: var=user
    # - name: Change file owner
    #   ansible.builtin.file:
    #     path: '../provision/files/provisioning.sh'
    #     owner: root
    #     group: root
    #     state: file
    #   register: out
    # - debug: var=out