- name: Pause until ready
  ansible.builtin.pause:
    prompt: |
      Microsd should be ready, resize root partition
      and/or place microsd in pi and boot. Input ip
      address of core machine, once it has finished booting.
      Packages will then install and the machine will reboot
      several times.
  register: command_output
  when: motioncore_ip is not defined or motioncore_ip == ""
- name: Set Ip of remote machine
  ansible.builtin.set_fact: 
    motioncore_ip: "{{ command_output.user_input }}" 
    cacheable: true
  when: motioncore_ip is not defined or motioncore_ip == ""
- name: Add host
  ansible.builtin.add_host:
    name: '{{ motioncore_ip }}'
    group: "motioncore"
- name: Remove host from known_hosts
  ansible.builtin.shell:
    cmd: ssh-keygen -R {{ motioncore_ip }}
- name: Wait for remote to reboot...
  ansible.builtin.wait_for_connection:
  delegate_to: "{{ motioncore_ip }}"
