- name: Install packages on remote machine
  community.general.rpm_ostree_pkg:
    name: "{{ motioncore_pkgs | list }}"
    state: present
  delegate_to: "{{ motioncore_ip }}"
- name: Add motion_user group
  ansible.builtin.group:
    name: motion_user
    state: present
  delegate_to: "{{ motioncore_ip }}"
- name: Add video group (getent issue https://github.com/coreos/rpm-ostree/issues/49#issuecomment-478091562)
  ansible.builtin.shell:
    cmd: echo video:x:39 >> /etc/group
  delegate_to: "{{ motioncore_ip }}"
- name: Add motion_user
  ansible.builtin.user:
    name: motion_user
    group: motion_user
    groups: video
    append: yes
  delegate_to: "{{ motioncore_ip }}"
- name: Enable lingering for motion_user
  ansible.builtin.shell:
      cmd: loginctl enable-linger motion_user
  delegate_to: "{{ motioncore_ip }}"
- name: Reboot host and wait for it to restart
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  delegate_to: "{{ motioncore_ip }}"