---
env_path: "{{ playbook_dir }}/.env"
env_values:
  - motion_email_address
  - motion_email_host 
  - motion_email_pass
image_build: /var/home/motion_user/image_build
ansible_required_packages:
  - python
  - python3-libselinux
  - python3-rpm
  - python3-firewall
motioncore_pkgs:
  - motion
  - fail2ban
  - audit
  - container-selinux
  
  # debugging selinux
  # - setools-console
  # - policycoreutils
  # - selinux-policy
  # - selinux-policy-devel
  # - libselinux-utils
  # - libselinux
  # - udica
# these packages are required.  Add extra packages to be installed above this line, as list members.
