- name: >-
   Install needed packages using the raw module
   ** Takes a long time! (rpm-ostree install) **
  ansible.builtin.raw: >-
    sudo rpm-ostree --idempotent install {{ rpmfusion_rpm_url + ' ' + ansible_required_packages }}
  delegate_to: "{{ hostvars['localhost']['remote_ip'] }}"
  register: install_output
- name: reboot after installing packages
  ansible.builtin.raw: systemd-run --on-active=5 shutdown -r now
  delegate_to: "{{ hostvars['localhost']['remote_ip'] }}"
  when: 'not (install_output.stdout_lines[-1:][0] == "No change.")'
- name: clear remote_ip when reboot
  ansible.builtin.set_fact:
    remote_ip: ""
  when: 'not ("No change." in install_output.stdout_lines)'
- name: Pause for 60 seconds
  ansible.builtin.pause:
    seconds: 120
  when: '(install_output.stdout_lines[-1:][0].find("No change.")) | bool'
# - name: Wait for SSH to be up
#   local_action: wait_for
#                 host="{{ hostvars['localhost']['remote_ip'] }}"
#                 port=22
#                 state=started
#   when: install_output.stdout.find('Run \"systemctl reboot\" to start a reboot')
