---
- name: | 
    Provision 3 - install python, rpmfusion, 
    add motion_user to video group and reboot.
    Takes a long time (rpm-ostree!).
  hosts: motioncore
  remote_user: core
  become: yes
  become_user: core
  become_method: sudo
  gather_facts: false
  tasks:
    - name: Install needed packages using the raw module
      ansible.builtin.raw: sudo rpm-ostree install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-37.noarch.rpm python libselinux-python && sudo usermod -aG video motion_user && sudo reboot
    - debug: var=python_result
    - name: Wait for remote to reboot...
      ansible.builtin.wait_for_connection:
