---
- name: Provision 1 - transpile to config.ign
  hosts: localhost
  connection: local
  vars_files:
    "{{ playbook_dir }}/../../vars.yaml"
  tasks:
    - name: transpile config.bu into config.ign
      ansible.builtin.shell:
        cmd: podman run --rm --interactive=True -v {{ playbook_dir }}/../../files:/files:Z quay.io/coreos/butane:release --files-dir /files --pretty --strict < files/config.bu > files/config.ign
