---
- debug:
    msg: "provisioning the micro sd card with coreos"
- name: Provision the micro-sd card
  hosts: localhost
  connection: local
  become: true
  vars_files:
    "{{ playbook_dir }}/../../vars.yaml"
  tasks:
    - name: Run script # shell needed to provide variable expansion etc
      ansible.builtin.shell:
        cmd: ./files/provisioning.sh
    - name: Pause until ready
      ansible.builtin.pause:
        prompt: "input ip address of core machine, once it has finished booting."
      register: command_output
    - set_fact:
        motioncore_ip: "{{ command_output.user_input }}"
    - name: Install packages on remote machine
      community.general.rpm_ostree_pkg:
        name: packages
        state: present
