- name: Get local packages for later conditional test for coreos-installer
  ansible.builtin.package_facts:
    manager: auto
  register: local_pkgs
- name: set pkg fact
  ansible.builtin.set_fact:
    local_pkgs: "{{ local_pkgs }}"
    cacheable: true
  # cleanup temp files etc
- name: Cleanup before beginning
  command: echo "this task will cleanup tempfiles"
  notify: "cleanup_handler"
- name: flush handlers
  meta: flush_handlers
  # templates
- name: Complete templates
  ansible.builtin.include_tasks:
    file: template.yaml
  # Provision the microsd card and setup the machine
- name: Provision machine
  ansible.builtin.import_tasks: provision.yaml
