---
- name: Copy files to provisioned machine
  hosts: "{{ motioncore_ip }}"
  become: yes
  become_method: machinectl
  become_user: motion_user
  vars:
    image_build: "/var/home/motion_user/image_build"
  tasks:
    - name: Copy files to remote machine
      copy:
        src: "{{ playbook_dir  }}/{{ item.src }}"
        dest: "{{ playbook_dir }}/{{ item.dest }}"
        mode: "{{ item.mode }}"
        owner: "{{ item.owner if item.owner is defined else owner | default(omit) }}"
        group: "{{ item.group if item.group is defined else group | default(omit) }}"
        serole: "{{ item.serole if item.serole is defined else serole | default(omit) }}"
        seuser: "{{ item.seuser if item.seuser is defined else seuser | default(omit) }}"
        setype: "{{ item.setype if item.setype is defined else setype | default(omit) }}"
      loop:
        - { src: './files/fail2ban.conf', dest: '/etc/fail2ban/fail2ban.conf', mode: "0640", owner: root, group: root }
        - { src: '.files/sshd.conf', dest: '/etc/fail2ban/jail.local.d/sshd.conf', mode: "0540", owner: "root", group: "root" }
        - { src: '.files/motion.conf', dest: '/etc/motion/motion.conf', mode: "0540", owner: "root", group: "video" }
        - { src: '.files/image_build/Dockerfile', dest: '{{ image_build }}/Dockerfile', mode: "0540", owner: "root", group: "video" }
        - { src: '.files/image_build/motion_mail.py', dest: '{{ image_build }}/motion_mail.py', mode: "0540", owner: "root", group: "video" }
