---
- block:
    - name: Pull Python Image - takes a while...
      containers.podman.podman_image:
        name: docker.io/library/python
        state: present
    - name: Build Custom Python Image
      containers.podman.podman_image:
        name: python
        tag: motioncore
        path: "{{ image_build }}"
        state: present
      register: build_output
    - name: Create email password secret
      containers.podman.podman_secret:
        state: present
        force: true
        name: motion_email_secret
        data: "{{ motion_email_pass }}"
  remote_user: core
  become: true
  become_user: motion_user