  # obtain ip address of remote host from user and set fact
- name: Get and set remote ip
  ansible.builtin.include_tasks: 
    file: provision/01_get_set_ip.yaml
- name: Install packages and reboot
  ansible.builtin.include_tasks: 
    file: provision/02_install_pkgs.yaml
    apply:
      remote_user: core
      become: yes
      become_user: root
      become_method: sudo
- name: Add and configure user
  ansible.builtin.include_tasks: 
    file: provision/03_add_user.yaml
    apply:
      remote_user: core
      become: yes
      become_user: root
      become_method: sudo
- name: flush handlers
  meta: flush_handlers