- block:
    - name: Create file template
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ role_path }}/files/templated/{{ item.dest }}"
        mode: "{{ item.mode }}"
        setype: "container_file_t"
        owner: "{{ item.owner | default(template_user)}}"
        group: "{{ item.group | default(template_user)}}"
      loop:
        - { src: 'sshd.conf.j2', dest: 'sshd.conf', mode: "0440" }
        - { src: 'motion.conf.j2', dest: 'motion.conf', mode: "0440" }
  vars:
    template_user: "{{ lookup('env', 'USER') }}"