- name: >-
   Install openvpn
   ** Takes a long time! (rpm-ostree install) **
  community.general.rpm_ostree_pkg:
    name: openvpn
    state: present
  remote_user: core
  become: yes
  become_user: root
  become_method: sudo
  register: openvpn_installed
  delegate_to: "{{ hostvars['localhost']['remote_ip'] }}"
- name: Add openvpn group (getent issue https://github.com/coreos/rpm-ostree/issues/49#issuecomment-478091562)
  ansible.builtin.shell:
    cmd: grep "openvpn:x:975:" /etc/group && echo "already in openvpn group" || echo "openvpn:x:975:" >> /etc/group
  remote_user: core
  become: yes
  become_user: root
  become_method: sudo
  register: openvpn_group_out
  delegate_to: "{{ hostvars['localhost']['remote_ip'] }}"
- name: Reboot
  ansible.builtin.reboot:
    msg: "Rebooting to install packages"
    pre_reboot_delay: 0
  remote_user: core
  become: yes
  become_user: root
  become_method: sudo
  delegate_to: "motioncore.local" # "{{ hostvars['localhost']['remote_ip'] }}"
  when: >- 
      openvpn_installed.needs_reboot 
      or "already in openvpn group" not in openvpn_group_out.stdout_lines 
# - name: Reboot
#   ansible.builtin.raw: systemd-run --on-active=5 shutdown -r now
#   delegate_to: "{{ hostvars['localhost']['remote_ip'] }}"
#   when: openvpn_installed.needs_reboot
# - name: Pause for 60 seconds
#   ansible.builtin.pause:
#     seconds: 60
#   when: openvpn_installed.needs_reboot
# - name: Wait for SSH to be up
#   local_action: wait_for
#                 host="{{ hostvars['localhost']['remote_ip'] }}"
#                 port=22
#                 state=started
#   when: openvpn_installed.needs_reboot
- name: Complete templates
  ansible.builtin.import_tasks: template.yaml
- name: copy openvpn directory
  ansible.builtin.synchronize:
    src: "{{ role_path }}/files/openvpn/"
    dest: /etc/openvpn/
    owner: false
    group: false
  remote_user: core
  become: yes
  become_user: root
  become_method: sudo
  tags: nordvpn_copy_openvpn
- name: copy systemd service
  ansible.builtin.copy:
    src: "{{ role_path }}/files/systemd/system/openvpn_rand.service"
    dest: /etc/systemd/system/
  remote_user: core
  become: yes
  become_user: root
  become_method: sudo
  tags: nordvpn_copy_unit_file
- name: Apply SELinux file context to openvpn
  ansible.builtin.command: restorecon -irv /etc/openvpn
  remote_user: core
  become: yes
  become_user: root
  become_method: sudo
  tags: nordvpn_selinux_openvpn
- name: Apply SELinux file context to systemd file
  ansible.builtin.command: restorecon -iv /etc/systemd/system/openvpn_rand.service
  remote_user: core
  become: yes
  become_user: root
  become_method: sudo
  tags: nordvpn_selinux_unit_file
- name: Enable and start openvpn_rand service
  ansible.builtin.systemd:
    name: openvpn_rand
    enabled: yes
    state: started
  remote_user: core
  become: yes
  become_user: root
  become_method: sudo
  tags: nordvpn_start_service

