---
- block:
    - name: Create directories
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
        setype: "{{ item.setype if item.setype is defined else setype | default(omit) }}"
        seuser: "{{ item.seuser if item.seuser is defined else seuser | default(omit) }}"
      loop:
        - { path: "/var/home/motion/", mode: "0700", owner: "motion", group: "root", setype: "motion_data_t", seuser: "system_u"}
        - { path: "/var/home/motion/files", mode: "0700", owner: "motion", group: "root", setype: "motion_data_t", seuser: "system_u"}
      delegate_to: "{{ remote_ip }}"
    # - name: Set selinux on file
    #   community.general.sefcontext:
    #     target: /root/files(/.*)?
    #     setype: container_file_t
    #     seuser: unconfined_u
    #     state: present
    #   delegate_to: "{{ remote_ip }}"
    - name: Copy files to remote machine
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
        owner: "{{ item.owner if item.owner is defined else owner | default(omit) }}"
        group: "{{ item.group if item.group is defined else group | default(omit) }}"
        serole: "{{ item.serole if item.serole is defined else serole | default(omit) }}"
        seuser: "{{ item.seuser if item.seuser is defined else seuser | default(omit) }}"
        setype: "{{ item.setype if item.setype is defined else setype | default(omit) }}"
      loop:
        - { src: '{{ role_path }}/files/fail2ban.conf', dest: '/etc/fail2ban/fail2ban.conf', mode: "0640", owner: root, group: root }
        - { src: '{{ role_path }}/files/templated/sshd.conf', dest: '/etc/fail2ban/jail.d/sshd.conf', mode: "0640", owner: "root", group: "root" }
        - { src: '{{ role_path }}/files/templated/motion.conf', dest: '/etc/motion/motion.conf', mode: "0640", owner: "root", group: "video" }
        - { src: '{{ role_path }}/files/templated/motion_mail.py', dest: '/var/home/motion/motion_mail.py', mode: "0500", owner: "motion", group: "root", setype: "motion_exec_t", seuser: "system_u"}
        - { src: '{{ role_path }}/files/motion_default', dest: '/etc/default/motion', mode: "0444", owner: "root", group: "root" }
        - { src: '{{ role_path }}/files/motion.service', dest: '/etc/systemd/system/motion.service', mode: "0640", owner: "root", group: "root" }
        - { src: '{{ role_path }}/files/policy_motioncore.te', dest: '/var/home/motion/policy_motioncore.te', mode: "0440", owner: "motion", group: "root" }
      delegate_to: "{{ remote_ip }}"
  remote_user: core
  notify: "mr_cleanup_handler"
  become: true
- name: flush handlers
  meta: flush_handlers
