---
- block:
   - name: install selinux policy module
     ansible.builtin.shell:
       cmd: >-
         cd /var/home/motion
         && /usr/bin/checkmodule -M -m -o policy_motioncore.mod policy_motioncore.te
         && /usr/bin/semodule_package -o policy_motioncore.pp -m policy_motioncore.mod
         && /usr/sbin/semodule -i policy_motioncore.pp
         && rm -rf policy_motioncore*
   - name: Mask motion.service
     ansible.builtin.systemd:
       name: motion.service
       masked: true
       enabled: false
       state: stopped
   - name: Start fail2ban.service
     ansible.builtin.service:
       name: fail2ban.service
       enabled: true
       state: started
       scope: system
   - name: Start motion.service
     ansible.builtin.systemd:
        name: motion
        enabled: true
        state: started
        scope: system
  remote_user: core
  become: true
  become_user: root
  become_method: sudo