- name: Remove templated files
  become: true
  become_user: root
  ansible.builtin.file:
    path: "{{ role_path }}/files/templated/{{ item }}"
    state: absent
  loop:
    - sshd.conf
  listen: "mr_cleanup_handler"
- name: Reboot remote and wait for it to restart
  become: true
  become_user: root
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  delegate_to: "{{ rpi4_coreos_ip }}"
  listen: "mr_reboot_handler"