---
- name: Import sub playbooks
  hosts: localhost
  connection: local
  vars:
    env_path: './.env'
    values:
      - motion_user_ssh_authorized_key
      # list more .env vars here
  tasks:
    - name: Read values from environment
      ansible.builtin.shell: "source {{env_path}}; echo ${{item|upper}}"
      register: output
      with_items: "{{ values }}"
      changed_when: false
    - name: Store read value
      ansible.builtin.set_fact:
        "{{ item.0 }}": "{{ item.1.stdout }}"
      when: '{{ item.0 }} is undefined'
      with_together:
        - "{{ values }}"
        - "{{ output.results }}"
      changed_when: false
- ansible.builtin.import_playbook: ./cleanup.yaml
- ansible.builtin.import_playbook: coreos_config/templates/template.yaml
- ansible.builtin.import_playbook: coreos_config/provision/provision1.yaml
# - ansible.builtin.import_playbook: coreos_config/provision/provision2.yaml
# - ansible.builtin.import_playbook: coreos_config/copy/copy.yaml
# - ansible.builtin.import_playbook: coreos_config/podman/podman.yaml
    
