- name: Read values from environment
  ansible.builtin.shell: "source {{env_path}}; echo ${{item|upper}}"
  register: output
  with_items: "{{ env_values }}"
  changed_when: false
- name: Store read value
  ansible.builtin.set_fact:
    "{{ item.0 }}": "{{ item.1.stdout }}"
  when: '{{ item.0 }} is undefined'
  with_together:
    - "{{ env_values }}"
    - "{{ output.results }}"
  changed_when: false
  # cleanup temp files etc
- name: Cleanup before beginning
  command: echo "this task will cleanup tempfiles"
  notify: "cleanup_handler"
- name: flush handlers
  meta: flush_handlers
  # templates
- name: Complete templates
  ansible.builtin.import_tasks: template.yaml
  # Provision the microsd card and setup the machine
- name: Provision machine
  ansible.builtin.import_tasks: provision.yaml
  # modify firewall rules
- name: Modify firewall rules
  ansible.builtin.import_tasks: firewall.yaml
  # copy configuration files
- name: Copy files to remote machine
  ansible.builtin.import_tasks: copy.yaml
  # setup podman
- name: Setup podman
  ansible.builtin.import_tasks: podman.yaml
  delegate_to: "{{ rpi4_coreos_ip }}"
- name: Start services
  ansible.builtin.import_tasks: run.yaml
  delegate_to: "{{ rpi4_coreos_ip }}"