---
- block:
    - name: Pull Python Image
      containers.podman.podman_image:
        name: docker.io/library/python
        state: present
    - name: Build Custom Python Image
      containers.podman.podman_image:
        name: python
        tag: motioncore
        path: "{{ image_build }}"
        state: present
      register: build_output
    - debug: var=build_output
    - name: Create secret
      containers.podman.podman_secret:
        state: present
        name: motion_secret
        data: "{{ lookup('password', '/dev/null length=32') }}"
  remote_user: core
  become: true
  become_user: motion_user